###

GET http://localhost:3000/customerInfo

###

GET http://localhost:3000/customerInfo/8

###
POST http://localhost:3000/customerInfo/mobile
Content-Type: application/json 

{
    "name":"Gokul",
    "Address" : "Chidambaram"
}

###

Put http://localhost:3000/customerInfo/3
Content-Type: application/json

{
    "Address" : "Medavakam",
    "product_name" : "Computer"
}

###
DELETE http://localhost:3000/customerInfo/41


###
###

GET http://localhost:3000/productInfo

###
GET http://localhost:3000/productInfo/3

###
POST http://localhost:3000/productInfo
Content-Type: application/json

{
    "product_name" : "Television"
}


###
PUT http://localhost:3000/productInfo/6
Content-Type: application/json

{
    "product_name" : "AC"
}


###
DELETE http://localhost:3000/productInfo/3

