###

GET http://localhost:3000/employeeInfo

###


GET http://localhost:3000/employeeInfo/6

###


POST http://localhost:3000/employeeInfo
Content-Type: application/json
 
{
    "name": "Arjun",
    "Address" : "Palani",
    "job_title" : "Data Analyst",
    "salary" : 25000
}

###
PUT http://localhost:3000/employeeInfo/6
Content-Type: application/json

{
    "name": "kjugug",
    "Address":"lilhkhg",
    "job_title":"Saleugs khvvv",
    "salary" : 10000

}

###
DELETE http://localhost:3000/employeeInfo/6


###
###
###
###

POST http://localhost:3000/users/employeeInfo
Content-Type: application/json

{
    "name": "yy",
    "Address" : "TTF pit shop",
    "job_title" : "Biker",
    "salary" : 100000
}

###

GET http://localhost:3000/users/employeeInfo

###

GET http://localhost:3000/users/employeeInfo/1

###

PUT http://localhost:3000/users/employeeInfo/7
Content-Type: application/json

{
    "name": "kjugug",
    "Address":"lilhkhg",
    "job_title":"Saleugs khvvv",
    "salary" : 10000000

}

###
DELETE http://localhost:3000/users/employeeInfo/7


###
GET  http://localhost:3000/page