###

GET http://localhost:3000/book

###

GET http://localhost:3000/book/10

###
POST http://localhost:3000/book
Content-Type: application/json 

{
    "book_name":"Dark Moon",
    "author_name" : "Akash"
}

###

Put http://localhost:3000/book/11
Content-Type: application/json

{
    "book_name" : "Harry Pottor"
}

###
DELETE http://localhost:3000/book/11


###
###

GET http://localhost:3000/author

###
GET http://localhost:3000/author/3

###
POST http://localhost:3000/author
Content-Type: application/json

{
    "author_name" : "Simon",
    "book_name" : "Equip Well"
}


###
PUT http://localhost:3000/author/5
Content-Type: application/json

{
    "author_name" : "samson"
}


###
DELETE http://localhost:3000/author/18

