###

GET http://localhost:3000/employeeInfo

###


GET http://localhost:3000/employeeInfo/1

###


POST http://localhost:3000/employeeInfo
Content-Type: application/json
 
{
    "name": "Dheena",
    "Address" : "Chidhambaram",
    "job_title" : "Data Analyst",
    "salary" : 40000
}

###
PUT http://localhost:3000/employeeInfo/16
Content-Type: application/json

{
    "name": "Dheena Dhayalan",
    "Address":"Cuddalore",
    "job_title":"Junior Engineer",
    "salary" : 35000
}

###
DELETE http://localhost:3000/employeeInfo/5


###
###
###
###

POST http://localhost:3000/users/employeeInfo
Content-Type: application/json

{
    "name": "yy",
    "Address" : "TTF pit shop",
    "job_title" : "Biker",
    "salary" : 100000
}

###

GET http://localhost:3000/users/employeeInfo

###

GET http://localhost:3000/users/employeeInfo/1

###

PUT http://localhost:3000/users/employeeInfo/7
Content-Type: application/json

{
    "name": "kjugug",
    "Address":"lilhkhg",
    "job_title":"Saleugs khvvv",
    "salary" : 10000000

}

###
DELETE http://localhost:3000/users/employeeInfo/7


